environment: prd

dex:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-methods: "*"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    className: "nginx-private"
  serviceAccountName: dex
  config:
    web:
      allowedOrigins: ['*']
    oauth2:
      responseTypes: [ "code" ]
      skipApprovalScreen: true
      alwaysShowLoginScreen: true
    storage:
      type: kubernetes
      config:
        inCluster: true
      enablePasswordDB: false