apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-api
spec:
  selector:
    matchLabels:
      app: bcs-api
  template:
    metadata:
      labels:
        app: bcs-api
    spec:
      containers:
        - name: bcs-api
          image: ghcr.io/alinflorin/bcs-api:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          env:
            - name: 'QDRANT__APIKEY'
              valueFrom:
                secretKeyRef:
                  name: bcs
                  key: apiKeyReadOnly
            - name: 'QDRANT__HOSTNAME'
              value: '{{ .Release.Name }}-qdrant'
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3