apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bcs
  labels:
    app.kubernetes.io/name: bcs
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/connection-proxy-header: "upgrade"
    nginx.ingress.kubernetes.io/upgrade: "websocket"

    # 🔒 Rate limiting annotations
    nginx.ingress.kubernetes.io/limit-connections: "1"
    nginx.ingress.kubernetes.io/limit-rpm: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
    nginx.ingress.kubernetes.io/limit-rate-after: "0"
spec:
  tls:
    - hosts:
        - bcs{{ if ne .Values.environment "prd" }}-{{ .Values.environment }}{{ end }}.internal.huna2.com
      secretName: bcs-tls
  rules:
    - host: bcs{{ if ne .Values.environment "prd" }}-{{ .Values.environment }}{{ end }}.internal.huna2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bcs-ui
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bcs-api
                port:
                  number: 80
          - path: /signalr
            pathType: Prefix
            backend:
              service:
                name: bcs-api
                port:
                  number: 80
