apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-ui
spec:
  selector:
    matchLabels:
      app: bcs-ui
  template:
    metadata:
      labels:
        app: bcs-ui
    spec:
      containers:
        - name: bcs-ui
          image: ghcr.io/alinflorin/bcs-ui:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3