name: bcs-api Docker CI

on:
  push:
    branches:
      - main
    paths: 
      - src/bcs-api/**

  pull_request:
    branches:
      - main
    paths: 
      - src/bcs-api/**

jobs:
  reusable-docker:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    uses: ./.github/workflows/reusable-docker-ci.yaml
    with:
      project: 'bcs-api'
      ci: true
      version: ${{ github.sha }}
    secrets: inherit