name: Chart CI

on:
  push:
    branches:
      - main
    paths: 
      - src/chart/**

  pull_request:
    branches:
      - main
    paths: 
      - src/chart/**

jobs:
  helm:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    uses: ./.github/workflows/reusable-helm-ci.yaml
    with:
      ci: true
      version: ${{ github.sha }}
    secrets: inherit