name: Chart CI

on:
  push:
    branches:
      - main
    paths: 
      - src/chart/**
      - .github/workflows/chart-ci.yaml
      - .github/workflows/reusable-helm-ci.yaml

  pull_request:
    branches:
      - main
    paths: 
      - src/chart/**
      - .github/workflows/chart-ci.yaml
      - .github/workflows/reusable-helm-ci.yaml

jobs:
  helm:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: none
    uses: ./.github/workflows/reusable-helm-ci.yaml
    with:
      ci: true
      version: ${{ github.sha }}