name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  MAJOR_MINOR: "1.0"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for fetching tags

      - name: Calculate version
        id: version
        run: |
          MAJOR_MINOR=${{ env.MAJOR_MINOR }}

          LAST_TAG=$(git tag --list "v$MAJOR_MINOR.*" --sort=-v:refname | head -n1)
          if [[ -z "$LAST_TAG" ]]; then
            PATCH=0
          else
            LAST_PATCH=${LAST_TAG##*.}
            PATCH=$((LAST_PATCH + 1))
          fi

          VERSION="$MAJOR_MINOR.$PATCH"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Export for use in other jobs
          echo "Calculated version: $VERSION"

  rename-run:
    needs: version
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Update the summary
        run: |
          VERSION="${{ needs.version.outputs.VERSION }}"
          PR_TITLE=""

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_TITLE="PR: ${{ github.event.pull_request.title }}"
          fi

          SUMMARY="Version: $VERSION"
          if [ -n "$PR_TITLE" ]; then
            SUMMARY="$PR_TITLE - $SUMMARY"
          fi

          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  analyze:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
        - language: javascript-typescript
          build-mode: none
        - language: csharp
          build-mode: autobuild

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET 9
      uses: actions/setup-dotnet@v1
      if: matrix.language == 'csharp'
      with:
        dotnet-version: 9.0.x

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  docker-build-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ui
          - name: api
    uses: ./.github/workflows/docker-build.yml
    needs: [version]
    with:
      name: bcs-${{ matrix.name }}
      path: ./src/${{ matrix.name }}
      version: ${{ needs.version.outputs.VERSION }}

  helm:
    runs-on: ubuntu-latest
    needs: [version]
    env:
      VERSION: ${{ needs.version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract and bump version
        id: version
        run: |
          sed -i "s/^version:.*/version: $VERSION/" src/chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" src/chart/Chart.yaml

      - name: Log in to GHCR for Helm
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Cache Helm dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: src/chart/charts
          key: ${{ runner.os }}-helm-deps-${{ hashFiles('src/chart/Chart.lock') }}
          restore-keys: |
            ${{ runner.os }}-helm-deps-

      - name: Add Helm repos
        working-directory: src/chart
        run: |
          if [ -f "./Chart.lock" ]; then
            yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./Chart.lock"  | sh --;
          fi

      - name: Download dependencies for Helm chart
        working-directory: src/chart
        if: ${{ steps.cache.outputs.cache-hit != true }}
        run: |
          helm dependency build

      - name: Package Helm chart
        working-directory: src/chart
        run: |
          helm package .

      - name: Push Helm chart to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        working-directory: src/chart
        run: |
          helm push bcs-*.tgz oci://ghcr.io/alinflorin/charts

  set-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: [version, docker-build-push, helm]
    env:
      VERSION: ${{ needs.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build-push, helm, version, set-version]
    env:
      VERSION: ${{ needs.version.outputs.VERSION }}
    strategy:
      matrix:
        environment: [stg, uat, prd]

    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Kubeconfig to file
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Substitute Secrets Action
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: "src/chart/values-${{ matrix.environment }}.yaml"
          substitutionRegex: \$\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(secrets) }}
          throwOnDataMissing: false

      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          use-cache: "true"
          tags: tag:mobile
          version: latest

      - name: Log in to GHCR for Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Deploy to ${{ matrix.environment }} environment with Helm
        run: |
          helm upgrade --kubeconfig ${{ github.workspace }}/kubeconfig.yaml --install --namespace bcs-${{ matrix.environment }} --create-namespace --values src/chart/values-${{ matrix.environment }}.yaml --set environment=${{ matrix.environment }} --version ${{ env.VERSION }} bcs oci://ghcr.io/alinflorin/charts/bcs

      - name: Remove kubeconfig file
        if: always()
        run: rm -rf ${{ github.workspace }}/kubeconfig.yaml || true