name: Release - Build Push Deploy

on:
  release:
    types: [released]

env:
  GHCR_ORG: ghcr.io/alinflorin

jobs:
  docker:
    if: ${{ github.event.release.target_commitish == 'main' }}
    strategy:
      matrix:
        project: ['bcs-ui', 'bcs-api']
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    uses: ./.github/workflows/reusable-docker-ci.yaml
    with:
      project: ${{ matrix.project }}
      ci: false
      version: ${{ github.ref_name }}
    secrets: inherit


  helm:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    if: ${{ github.event.release.target_commitish == 'main' }}
    uses: ./.github/workflows/reusable-helm-ci.yaml
    with:
      ci: false
      version: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    needs: [docker, helm]
    strategy:
      matrix:
        environment: [stg, uat, prd]
    if: ${{ github.event.release.target_commitish == 'main' }}
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ matrix.environment }}
      version: ${{ github.ref_name }}
      uninstall: false
    secrets: inherit