name: Reusable Docker CI

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

jobs:
  docker:
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']

    runs-on: ${{ matrix.platform }}

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ inputs.project }}
          platforms: ${{ matrix.platform }}
          tags: ${{ inputs.project }}:${{ github.sha }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: VERSION=${{ github.sha }}
          load: true

      - name: Scan image with Trivy and generate SARIF
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ inputs.project }}:${{ github.sha }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          format: sarif
          output: trivy-${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}.sarif
