name: Reusable Docker CI

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      version:
        type: string
        required: true
      ci:
        type: boolean
        required: true

jobs:
  docker:
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']

    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}

    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        if: ${{ inputs.ci == false }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/${{ inputs.project }}
          platforms: ${{ matrix.platform }}
          tags: ${{ inputs.ci == false && 'ghcr.io/alinflorin/' || '' }}${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: VERSION=${{ inputs.version }}
          load: true
          push: ${{ inputs.ci == false }}

      - name: Scan image with Trivy and generate SARIF
        if: ${{ inputs.ci == true }}
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}:${{ inputs.version }}
          format: sarif
          output: trivy-${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Upload SARIF to GitHub
        if: ${{ inputs.ci == true }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ inputs.project }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}.sarif
