name: Reusable Docker CI

on:
  workflow_call: 
    inputs:
      project:
        type: string
        required: true

jobs:
  docker:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
            suffix: '-amd64'
          - platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            suffix: '-arm64'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ inputs.project }}-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ inputs.project }}-${{ runner.os }}-

      - name: Build multi-arch Docker image with cache
        run: |
          echo "Building project: ${{ inputs.project }}${{ matrix.suffix }}"
          docker buildx build \
            --platform ${{ matrix.platform }} \
            -t ${{ inputs.project }}:${{ github.sha }}${{ matrix.suffix }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --build-arg VERSION=${{ github.sha }} \
            --load \
            ./src/${{ inputs.project }}

            
      - name: Scan image with Trivy and generate SARIF
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ inputs.project }}:${{ github.sha }}${{ matrix.suffix }}
          format: sarif
          output: trivy-${{ inputs.project }}${{ matrix.suffix }}.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ inputs.project }}${{ matrix.suffix }}.sarif

      - name: Save updated Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
