name: Manual Uninstall

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to uninstall"
        required: true
        type: choice
        options:
          - stg
          - uat
          - prd

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.environment }}
      version: '-'
      uninstall: true